---
- name: EXECUTE SHOW VERSION COMMAND ON TARGET DEVICES
  hosts: all
  gather_facts: false
  tasks:
    - name: RUN COMMAND
      cisco.ios.ios_command:
        commands: show version
      register: result

    - name: DISPLAY OUTPUT
      ansible.builtin.debug:
        var: result
